name: Run tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python setup.py install
      - run: nginx-static-analysis --help
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run general testsuite
        run: ./runtests.sh
        shell: bash
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
